spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show_sql: true

  flyway:
    enabled: false

sms:
  twilio:
    enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    dev.fnvir.kajz: debug
    org.apache.kafka: warn
