spring:
  application:
    name: NotificationService
  
  threads.virtual.enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8444/realms/kajz

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show_sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true

  data:
    web:
      pageable:
        max-page-size: 100

  jackson:
      mapper:
        accept-case-insensitive-enums: true

  kafka:
    bootstrap-servers:
      - localhost:9094
    producer:
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: snappy
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "*"
        enable.idempotence: true
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
#        spring.json.value.default.type: com.fasterxml.jackson.databind.node.ObjectNode
  
  webflux:
    apiversion:
      default: 1
      supported: 1
      use:
        header: X-API-Version

email:
  provider: gmail
  username: ${MAIL_USERNAME} # use env var in ide to set
  password: ${MAIL_PASSWORD}
  sender-address: ${MAIL_ADDRESS}
  properties:
    smtp:
      auth: true
      connectiontimeout: 5000
      starttls:
        enable: true
#  microsoft:
#    client-id: ${MS_CLIENT_ID}
#    client-secret: ${MS_CLIENT_SECRET}
#    tenant-id: ${MS_TENANT_ID}

sms:
  twilio:
    enabled: true
    account-sid: ${TWILIO_ACC_SID} # use env var in ide to set
    auth-token: ${TWILIO_AUTH_TOKEN}
    phone-number: ${TWILIO_PHN_NUMBER}

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
springdoc:
  swagger-ui:
    path: /notification-service/swagger-ui.html
  api-docs:
    path: /notification-service/v3/api-docs

server:
  port: 8082

management:
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    dev.fnvir.kajz: debug
    com.netflix.discovery: warn
    org.apache.kafka.clients.admin.internals: warn
