spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/storagedb
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

storage:
  aws:
    s3:
      auto-create-bucket: false
  azure:
    blob:
      auto-create-container: false
      
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

eureka:
  client:
    enabled: true

