services:
  keycloak-db:
    image: postgres:18.1-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${COMMON_DB_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    ports:
      - ${KEYCLOAK_DB_HOST_PORT}:5432
    volumes:
      - ../../resources/kajz/db/keycloakdb:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COMMON_DB_USER} -d ${KEYCLOAK_DB_NAME}"]
      interval: 20s
      start_period: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 64M
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always

  notification-db:
    image: postgres:18.1-alpine
    container_name: notification-db
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${COMMON_DB_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    ports:
      - "${NOTIFICATION_DB_HOST_PORT}:5432"
    volumes:
      - ../../resources/kajz/db/notificationdb:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${COMMON_DB_USER} -d ${NOTIFICATION_DB_NAME}" ]
      interval: 20s
      start_period: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 64M
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always

  keycloak:
    build: ./keycloak
    container_name: keycloak
    command: start --optimized
    environment:
      # bootstrap admin
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_SPI_ADMIN_REALM: master

      # db config
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${COMMON_DB_USER}
      KC_DB_PASSWORD: ${COMMON_DB_PASSWORD}

      # config
      KC_CACHE: local

      KC_HTTP_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: ${KEYCLOAK_HOST_NAME}
      KC_HOSTNAME_STRICT_HTTPS: "false"

      KC_PROXY_HEADERS: xforwarded
      # KC_PROXY_TRUSTED_ADDRESSES: ...
      
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - ${KEYCLOAK_HOST_PORT}:8080
    depends_on:
      - keycloak-db
    networks:
      - backend_network
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck {public static void main(String[] args) throws Exception {System.exit(200 ==((java.net.HttpURLConnection)new java.net.URI(args[0]).toURL().openConnection()).getResponseCode()?0:1);}}" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: "1"
          memory: 1200M
    restart: always

  redis:
    container_name: redis
    image: redis:8.4-alpine
    command: "redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 1G
        reservations:
          cpus: '0.4'
          memory: 512M
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    restart: always

  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: XLpix64zRACE8JMcYDTO5Q
    volumes:
      - ../../resources/kajz/kafka/data:/var/lib/kafka/data
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 400M
        limits:
          cpus: '1'
          memory: 1.2G
    restart: always
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 9060:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 512M

  service-registry:
    build: service-registry
    container_name: service-registry-container
    hostname: service-registry
    environment:
      SERVER_PORT: 8761
    ports:
      - "${DISCOVERY_SERVER_HOST_PORT}:8761"
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 400M
        limits:
          cpus: '1'
          memory: 512M
    healthcheck:
      test: curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 5
  
  api-gateway:
    build: api-gateway
    container_name: api-gateway-container
    hostname: api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      SERVER_PORT: 8080
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_TRUSTED_PROXIES: ".*"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${API_GATEWAY_HOST_PORT}:8080"
    networks:
      - backend_network
    volumes:
      - ../../resources/kajz/apigateway/certificates:/app/certificates
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 450M
        limits:
          cpus: '1'
          memory: 1G

  auth-service:
    build: auth-service
    container_name: auth-service-container
    hostname: auth-service
    environment:
      KEYCLOAK_SERVER_URL: http://host.docker.internal:8444
      KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_CLIENT_ID: ${EMAIL_CLIENT_ID}
      EMAIL_CLIENT_SECRET: ${EMAIL_CLIENT_SECRET}
      EMAIL_TENANT_ID: ${EMAIL_TENANT_ID}
      EMAIL_SCOPE: ${EMAIL_SCOPE}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      SERVER_PORT: 8080
    ports:
      - "${AUTH_SERVICE_HOST_PORT}:8080"
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 300M
        limits:
          cpus: '1'
          memory: 1G
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notification-service:
    build: notification-service
    container_name: notification-service-container
    hostname: notification-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/${NOTIFICATION_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${COMMON_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${COMMON_DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://${KEYCLOAK_HOST_NAME}:${KEYCLOAK_HOST_PORT}/realms/${KEYCLOAK_USER_REALM}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8080
      EMAIL_PROVIDER: ${EMAIL_PROVIDER}
      EMAIL_USERNAME: ${EMAIL_SMTP_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      EMAIL_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SENDER_ADDRESS: ${EMAIL_SENDER_ADDRESS}
      SMS_TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      SMS_TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      SMS_TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
    ports:
      - "${NOTIFICATION_SERVICE_HOST_PORT}:8080"
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 300M
        limits:
          cpus: '1'
          memory: 1G
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    user: 0:0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 6060:80
    volumes:
      - ../../resources/kajz/pgadmin:/var/lib/pgadmin
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.5'
          memory: 400M
    restart: always

volumes:
  redis_data:

networks:
  backend_network:
