spring:
  application:
    name: AuthService
  threads:
    virtual.enabled: true

keycloak:
  server-url: http://host.docker.internal:8444
  admin-realm: master
  admin-username: admin
  admin-password: admin1234
  admin-client-id: admin-cli
  user-realm: kajz
  user-client-id: backend-authservice
  
springdoc:
  swagger-ui:
    path: /auth-service/swagger-ui.html
  api-docs:
    path: /auth-service/v3/api-docs

server:
  port: 8081
  forward-headers-strategy: framework
  
eureka:
  instance:
    prefer-ip-address: true

  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    com.netflix.discovery: warn