name: notificationservice-tests

on:
  push:
    branches: [ "**" ]
    paths:
      - 'kajz/notification-service/src/**'
      - 'kajz/notification-service/pom.xml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'kajz/notification-service/src/**'
      - 'kajz/notification-service/pom.xml'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kajz/notification-service
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: 'kajz/notification-service/pom.xml'
    - name: Build and Test with Maven
      run: mvn -B clean verify -Dspring.profiles.active=test
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
        ENABLE_TC: true
